version: '3.7'
services:
  frp-letsencrypt:
    container_name: frp-letsencrypt
    build:
      context: ../..
    environment:
      - FRP_SSL_PROXY_EMAIL=test@example.com
      - FRP_SSL_PROXY_PRODUCTION=false
      - FRP_SSL_PROXY_HTTP_PORT=80
      - FRP_SSL_PROXY_HTTPS_PORT=443
      - FRP_SSL_PROXY_LETSENCRYPT_PORT=9999
      - FRP_SSL_PROXY_SUBDOMAIN_HOST=tunnel.example.com
      - FRP_SSL_PROXY_PROXY_TARGET=http://frp-server:80
      - FRP_SSL_PROXY_API_HTTP_PORT=9002
      - FRP_SSL_PROXY_X_FORWARD=true
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - '80:80'
      - '443:443'
  frp-server:
    container_name: frp-server
    build:
      context: frp-server
      args:
        - FRP_VERSION=0.36.2
        - FRP_TIMEZONE=Europe/Paris
    environment:
      - FRP_SUBDOMAIN_HOST=tunnel.example.com
      - FRP_VHOST_HTTP_PORT=80
      - FRP_VHOST_HTTPS_PORT=443
      - FRP_BIND_PORT=7000
      - FRP_BIND_UDP_PORT=7001
      - FRP_DASHBOARD_USER=admin
      - FRP_DASHBOARD_PASSWORD=admin123
      - FRP_TOKEN=123456789
      - FRP_ALLOW_PORTS=30000-30060
      - FRP_SSL_HOST=frp-letsencrypt:9002
    volumes:
      - ./data:/app/config
    ports:
      - '7000:7000'
      - '7500:7500'
      - '30000-30060:30000-30060'
